server:
 port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://192.168.1.91/r/spring-config-repo/mule-esb
          username: spring.config.server
          password: gitpassw0rd
